FROM linuxserver/qbittorrent:4.1.9.99201911190849-6738-0b055d8ubuntu18.04.1-ls53

COPY ./anime-scripts /scripts

RUN apt update
RUN apt install -y python3          
RUN apt install -y python3-requests
RUN apt install -y ffmpeg 
